version: '3.3'
services:
  keycloak-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "keycloak-service"
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - keycloaknet
  spring-service:
    build:
      context: .
      dockerfile: Api.Dockerfile
    container_name: "spring-service"
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - keycloaknet
    depends_on:
      - keycloak-service
    links:
      - keycloak-service

networks:
  keycloaknet:
